spring:
  application:
    name: contact-book

  datasource:
    url: jdbc:postgresql://localhost:5432/contact_book
    driver-class-name: org.postgresql.Driver
    username: contacts_db
    password: contacts_db

  jpa:
    properties:
      hibernate:
        default_schema: contacts

  flyway:
    url: jdbc:postgresql://localhost:5432/contact_book
    schemas: contacts
    user: contacts_db
    password: contacts_db

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

logging:
  level:
    com.university.contactbook: DEBUG

upload:
  path: C:\Users\farallel\Desktop\upload